---
  Style/Documentation:
    Enabled: false

  Style/FrozenStringLiteralComment:
    Enabled: false

  Layout/SpaceAroundMethodCallOperator:
    Enabled: true

  Lint/RaiseException:
    Enabled: false

  Lint/StructNewOverride:
    Enabled: false

  Style/ExponentialNotation:
    Enabled: false

  Style/HashEachMethods:
    Enabled: false

  Style/HashTransformValues:
    Enabled: false

  Style/HashTransformKeys:
    Enabled: false

  Layout/LineLength:
    Max: 110

  Metrics/MethodLength:
    Max: 20

  Metrics/BlockLength:
    Max: 50

  Metrics/AbcSize:
    Max: 30

  Metrics/CyclomaticComplexity:
    Max: 15

  Metrics/PerceivedComplexity:
    Max: 15
